package com.hasnat.optimum.common.enums;
public enum ApprovalDocumentType {
    STORE_REQUISITION, YARN_STORE_REQUISITION, STORE_PURCHASE_REQUISITION,
    PURCHASE_REQUISITION, PURCHASE_ORDER, YARN_PURCHASE_ORDER, PURCHASE_RETURN,
    SUPPLIER_CREDIT_NOTE, GOODS_RECEIVING_NOTE, YARN_GOODS_RECEIVING_NOTE,
    STOCK_ADJUSTMENT, STOCK_TRANSFER, SALES_QUOTATION, SALES_ORDER,
    YARN_SALES_ORDER, SALES_DELIVERY, YARN_SALES_DELIVERY, SALES_INVOICE,
    SALES_RETURN, JOURNAL_ENTRY, JOURNAL_VOUCHER, PAYMENT_VOUCHER,
    RECEIPT_VOUCHER, CONTRA_VOUCHER, EXPENSE_VOUCHER, PRODUCTION_ORDER,
    WORK_ORDER, MATERIAL_REQUISITION, MATERIAL_ISSUE, PRODUCTION_PLAN,
    LEAVE_APPLICATION, ATTENDANCE_ADJUSTMENT, OVERTIME_REQUEST,
    LOAN_APPLICATION, ADVANCE_REQUEST, EXPENSE_CLAIM, EXPORT_SALES_ORDER,
    YARN_RECEIVE, CUSTOMER_REGISTRATION, SUPPLIER_REGISTRATION, USER_ACCESS_REQUEST
}
