package com.hasnat.optimum.common.enums;
public enum DocumentType {
    SALES_QUOTATION, SALES_ORDER, DELIVERY_ORDER, DELIVERY_CHALLAN, SALES_INVOICE,
    PURCHASE_REQUISITION, REQUEST_FOR_QUOTATION, COMPARATIVE_STATEMENT, PURCHASE_ORDER,
    GOODS_RECEIPT_NOTE, PURCHASE_INVOICE, STORE_REQUISITION, MATERIAL_ISSUE,
    MATERIAL_RECEIVE, STOCK_TRANSFER, STOCK_ADJUSTMENT, PRODUCTION_ORDER,
    PRODUCTION_RECIPE, PRODUCTION_REQUISITION, PRODUCTION_MATERIAL_ISSUE,
    FINISHED_GOODS_RECEIVE, EXPORT_PROFORMA_INVOICE, IMPORT_PROFORMA_INVOICE,
    LETTER_OF_CREDIT, DEBIT_NOTE, CREDIT_NOTE
}
