package com.hasnat.optimum.common.enums;
public enum ModuleType {
    GENERAL_LEDGER, ACCOUNTS_PAYABLE, ACCOUNTS_RECEIVABLE, CASH_MANAGEMENT,
    BANK_RECONCILIATION, PROCUREMENT, PURCHASE, SALES, SALES_ORDER, INVENTORY,
    WAREHOUSE, PRODUCTION, YARN_PRODUCTION, QUALITY_CONTROL, PAYROLL,
    HUMAN_RESOURCE, FIXED_ASSETS, IMPORT_EXPORT, LC_MANAGEMENT, SYSTEM, REPORTING
}
