package com.hasnat.optimum.common.enums;
public enum TransactionType {
    PURCHASE_INVOICE, PURCHASE_RETURN, PURCHASE_ORDER, GRN, SALES_INVOICE,
    SALES_RETURN, SALES_ORDER, DELIVERY_NOTE, SUPPLIER_PAYMENT, CUSTOMER_RECEIPT,
    ADVANCE_PAYMENT, ADVANCE_RECEIPT, STOCK_RECEIPT, STOCK_ISSUE, STOCK_TRANSFER,
    STOCK_ADJUSTMENT, PRODUCTION_ISSUE, PRODUCTION_RECEIPT, EXPENSE_CLAIM,
    PETTY_CASH, SALARY_PROCESSING, SALARY_PAYMENT, ASSET_PURCHASE, ASSET_DISPOSAL,
    DEPRECIATION, LC_OPENING, LC_AMENDMENT, LC_PAYMENT, JOURNAL_ENTRY,
    OPENING_BALANCE, CLOSING_ENTRY
}
